apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-streaming
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
        - name: video-streaming
          image: $CONTAINER_REGISTRY/video-streaming:$VERSION
          imagePullPolicy: IfNotPresent
          env:
            - name: VIDEO_STORAGE_HOST
              value: video-storage
            - name: VIDEO_STORAGE_PORT
              value: "80"
            - name: DBHOST
              value: mongodb://db:27017
            - name: DBNAME
              value: video-streaming
            - name: PORT
              value: "4000"
            - name: RABBIT
              value: amqp://test:test@rabbit:5672
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming
spec:
  selector:
    app: video-streaming
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
